---
version: "3.8"


services:

  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    networks: 
      - main-overlay-network
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - type: bind
        source: ${APPS_DATA}/postgres
        target: /var/lib/postgresql/data/
      - type: bind
        source: ${APPS_SETTINGS}/postgres/postgres.conf
        target: /etc/postgresql/postgresql.conf
    expose:
      - 5432
    env_file: 
      - ${APPS_ENV}/postgres.env
    environment:
      PGDATA: /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always


networks:
  main-overlay-network:
    name: main-overlay-network
    external: true
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
