---
version: "3.8"


services:

  postgres:
    image: postgres:13
    container_name: postgres
    networks: 
      - main-overlay-network
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - type: bind
        source: ${APPS_DATA}/postgres
        target: /var/lib/postgresql/data/
      - type: bind
        source: ${APPS_SETTINGS}/postgres/postgres.conf
        target: /etc/postgresql/postgresql.conf
    ports:
      - target: 5432
        published: 5432
        mode: host
    env_file: 
      - ${APPS_ENV}/postgres.env
    environment:
      PGDATA: /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  
networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true
