---
version: "3.8"


services:

  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    networks: 
      - main-network
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data/
      - type: bind
        source: ./postgres.conf
        target: /etc/postgresql/postgresql.conf
    expose:
      - 5432
    env_file:
      - ./postgres.env
    environment:
      PGDATA: /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always


networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
    attachable: false


volumes:
  postgres-volume:
